import { resolveHost } from './deployment.js';
/**
 * Generates a Windows installer script (NSIS) for the branded launcher. NSIS is
 * the same engine electron-builder uses; emitting an .nsi lets owners build an
 * installer even outside electron-builder, and documents exactly what the
 * installer does: install the launcher, drop config, create shortcuts and
 * register an uninstaller.
 */
export function generateNsisInstaller(project) {
    const scheme = project.domain.useHttps ? 'https' : 'http';
    const apiBase = `${scheme}://${resolveHost(project)}`;
    const appName = project.meta.serverName || project.meta.name;
    const safeName = appName.replace(/[^A-Za-z0-9 ]/g, '');
    return `; NSIS installer for ${appName} launcher — generated by ForgeLink.
!include "MUI2.nsh"

Name "${safeName} Launcher"
OutFile "${safeName}-Setup.exe"
InstallDir "$PROGRAMFILES64\\${safeName}"
InstallDirRegKey HKCU "Software\\${safeName}" ""
RequestExecutionLevel admin

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"

  ; Launcher binaries are staged next to this script under \\launcher.
  File /r "launcher\\*.*"

  ; Drop the server configuration the launcher reads on first run.
  FileOpen $0 "$INSTDIR\\launcher-config.json" w
  FileWrite $0 '{"apiBase":"${apiBase}","serverId":"${project.id}","serverName":"${jsonEscape(appName)}"}'
  FileClose $0

  ; Shortcuts.
  CreateDirectory "$SMPROGRAMS\\${safeName}"
  CreateShortcut  "$SMPROGRAMS\\${safeName}\\${safeName} Launcher.lnk" "$INSTDIR\\${safeName}.exe"
  CreateShortcut  "$DESKTOP\\${safeName} Launcher.lnk" "$INSTDIR\\${safeName}.exe"

  ; Uninstaller + Add/Remove Programs registration.
  WriteUninstaller "$INSTDIR\\Uninstall.exe"
  WriteRegStr HKCU "Software\\${safeName}" "" $INSTDIR
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${safeName}" \\
    "DisplayName" "${safeName} Launcher"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${safeName}" \\
    "UninstallString" "$INSTDIR\\Uninstall.exe"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${safeName}" \\
    "DisplayVersion" "${project.meta.version}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${safeName}" \\
    "Publisher" "${jsonEscape(project.meta.owner)}"
SectionEnd

Section "Uninstall"
  Delete "$DESKTOP\\${safeName} Launcher.lnk"
  RMDir /r "$SMPROGRAMS\\${safeName}"
  RMDir /r "$INSTDIR"
  DeleteRegKey HKCU "Software\\${safeName}"
  DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${safeName}"
SectionEnd
`;
}
function jsonEscape(s) {
    return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
/**
 * electron-builder config for producing the actual branded launcher installer.
 * Written into the launcher output so `electron-builder` can be run against it.
 */
export function generateElectronBuilderConfig(project) {
    const appName = (project.meta.serverName || project.meta.name).replace(/[^A-Za-z0-9 ]/g, '');
    const appId = `com.forgelink.${project.id.replace(/[^a-z0-9]/gi, '').slice(0, 24)}`;
    return JSON.stringify({
        appId,
        productName: `${appName} Launcher`,
        copyright: `© ${new Date().getFullYear()} ${project.meta.owner}`,
        directories: { output: 'release' },
        files: ['dist/**/*', 'dist-electron/**/*', 'launcher-config.json'],
        win: {
            target: [{ target: 'nsis', arch: ['x64'] }],
            icon: project.branding.launcherIcon || undefined,
        },
        nsis: {
            oneClick: false,
            allowToChangeInstallationDirectory: true,
            createDesktopShortcut: true,
            createStartMenuShortcut: true,
            shortcutName: `${appName} Launcher`,
        },
    }, null, 2);
}
//# sourceMappingURL=installer.js.map